### ISSUE TITLE
Different doki theme for different windows in vscode

### ISSUE THREAD

**Issue by GabrielLCHeng** [doki-theme/doki-theme-vscode#193]
Let says I open two vscode windows, each doing different stuff, and I would like to have different doki sticker/theme/background for each window. Is there any way to get this?

**Comment by Unthrottled** [comment]
That'd be cool (I'd definitely use that), but I don't think there is a way to do that.

The sticker & background are coupled to the VSCode CSS, so any new instance of the same VS Code will have the same CSS assets. There isn't a way to control that without making our own VSCode or having different versions of VSCode installed.

I also don't think there is a way to support that. If that ever changes though, will be sure to add that feature, because I'd like to have a different theme for each project as well.
