### ISSUE TITLE
Sticker Installation Error

### ISSUE THREAD

**Issue by RahulARanger** [doki-theme/doki-theme-vscode#35]
**Describe the bug**

I recently updated vscode insiders so when I tried to install stickers(why reinstall ?, workaround for #26 ) I got this error as in the screenshot.
The themes are working fine. Installing Stickers is a problem.
![issue1](https://user-images.githubusercontent.com/57987728/100589696-71b7c500-3319-11eb-9adf-a80de9fef62c.PNG)

Sorry, this is my third issue. That shows how I love this repository. 

I would love to hear some solution.

**Environment**

Version: 1.52.0-insider (user setup)
Commit: f47aae014cf8567f648e68369d66b4106ae89f08
Date: 2020-11-30T06:08:34.438Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Windows_NT x64 10.0.20262

**Comment by Unthrottled** [comment]
Hey Friend! So I was able to reproduce the issue and verify the fix. The extension has been published. Feel free to open the issue again if the new release doesn't work for you. 

Also don't feel bad about reporting issues, I prioritize any `Doki-Theme` plugin bug fixes above everything else (that's why respond so quick :smile: )

**Comment by RahulARanger** [comment]
Thank You So Much for the quick response and fix.

Now I could again get the feel of working along with my waifu.
