### ISSUE TITLE
On the changelog, the sticker is under the images instead of the top

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-vscode#86]
**Describe the bug**

When opening the changelog, the sticker will be under the images instead of the top.

**To Reproduce**

1. Open the changelog

**Expected Behavior**

The sticker is on top of the images.

**Environment**

Version: 1.58.0-insider (user setup)
Commit: 012b14606f75ec4fed90d7ab4154f63dffab9503
Date: 2021-06-11T05:14:11.473Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
Doki Theme: 13.1.0

**Screenshots**

![image](https://user-images.githubusercontent.com/11861253/122090896-4046a880-cdd6-11eb-8db3-52bb11b58eab.png)

**Comment by Unthrottled** [comment]
There's no small detail that gets past you, is there? 

I'll not be a lazy turd and fix that, thank you for caring!

**Comment by justalemon** [comment]
> There's no small detail that gets past you, is there?

More like "I manage to break everything I touch without actively trying".

Think I almost bricked my PS Vita less than 24 hours after I got my hands on it xd

**Comment by Unthrottled** [comment]
Thank you for taking the time to report this issue. I've published the release and it is available.

Just as a small detail, not that it matters, but the backgrounds aren't transparent. I use a background image that already has a set opacity. So that's why some parts might be brighter than others, if there are more than one elements overlapping each other.
