### ISSUE TITLE
Settings dissapear when setting custom theme

### ISSUE THREAD

**Issue by ghost** [doki-theme/doki-theme-vscode#98]
**Describe the bug**
When selecting a custom theme, the settings dissapear. They are still there, but they are invisible.

**To Reproduce**
1. Set a custom theme using the Doki Theme extension
2. Reste VSC
3. See results

**Expected Behavior**
Only image should change, but the settings dissapear and i have to reinstall VSC to reset it.

**Environment**
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

Doki Theme version: v15.0.0

**Screenshots**
Its like this with every theme i've chosen.
![Screenshot1](https://user-images.githubusercontent.com/78029616/128830323-07a17cd4-dd1b-4db4-ac65-71aefefd0f95.png)
![Screenshot2](https://user-images.githubusercontent.com/78029616/128830971-4e02377a-0a92-460e-86c6-a7fb073fa815.png)

**Comment by Unthrottled** [comment]
Hey!

So I am having a hard time reproducing the issue.

Here is what I was doing:

https://user-images.githubusercontent.com/15972415/128948581-8b24f7bb-0e41-4ddb-9850-6c71332725d4.mp4

My setup

```
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042
```


Do you have any special characters in the path you are trying to set? 比如汉字或者 русские иероглифы ǫ̴̼̹̍͆̕r̶͉͚͑ ̵̙̺̒̇̽͗è̶͓͉̫ͅv̷̢̪̪͙̟̏ḛ̷̡͓̂̇̓̒͝n̷̰̦̓̈́ ̷̜̲̰̦͛́̄s̷̡̛̟̤̗̭̒̈́̚o̵̰͒̕͜m̵͈͔̘̈̈̆̉̏ḙ̷̻̯͎̦͌̀̒͝ṫ̵̨̹͒͂̂̽ͅh̷̭̻̲̋̅i̶̘͑ṇ̴͖̻̠͔̈́g̷̡̠̓̕͝ ̵͙̼̯͉̣̍̽̄́w̷̝̼͋̔̐͝i̵̡̦̳̓t̵̼́h̶̥̓ ̴̳͇̼̩̈̇̿ͅd̴̬̝̗̝̖͑i̶̛̼͎͔̼̻͌̂̇̔ȁ̵͓̹͕͔̯͐̈́̓c̸̲͗̄̽̏r̷̛̗͉̆̑̄̂i̷̡̿̒̀̀͠ț̵̡̛͓̈́͐̏i̵̦͔̠͋̈́̾̐͒c̸̙̥̣͚̃̀̓̂ṡ̵͎̙̐?̴͓̱̣͚̌

**Comment by Nexuzzzz** [comment]
Nope, the path is "C:\Users\scrubbed\Downloads\cultured.jpg" (without the quotation marks)

**Comment by Unthrottled** [comment]
Hmm, you're going to have to a bit of investigation for me then. You'll probably need to look through the logs of VSCode to see if there is anything suspect. I think there is a `Developer: Open Logs Folder` command that shows all the logs, there is also a `Developer: Open Extensions Logs Folder` command. 

If that sounds like too much work, you can always just edit the `settings.json` instead of using the ui editor, you didn't say that was broken.

**Comment by Nexuzzzz** [comment]
> Hmm, you're going to have to a bit of investigation for me then. You'll probably need to look through the logs of VSCode to see if there is anything suspect. I think there is a `Developer: Open Logs Folder` command that shows all the logs, there is also a `Developer: Open Extensions Logs Folder` command.
> 
> If that sounds like too much work, you can always just edit the `settings.json` instead of using the ui editor, you didn't say that was broken.

I tried that too, if i then reinstall vsc it will say **Error while installing Onyx Theme**, the logs don't show any errors too. Could it be that when selecting a custom theme, the current Doki wallpaper gets overwritten (Because when editing the settings.json file, and later removing the custom wallpaper i still get my old Doki wallpaper)?

**Comment by Unthrottled** [comment]
> Because when editing the settings.json file, and later removing the custom wallpaper i still get my old Doki wallpaper

That's the way it was designed to work. I was too lazy to write code to check to see if the user previously had the wallpaper installed before installing the custom asset. That way when they remove it it puts the default one back up, which is what they had before. 

So I just went with, you remove the custom wallpaper, you get the other wallpaper instead. If you want it gone, just `Remove Stickers/Wallpaper`. 

> Error while installing Onyx Theme,

That one is probably my bad. I've noticed that when specifying a custom asset, if you've got the path wrong, then it throws up the error screen. Probably should change that message that is brought up to `Hey Silly! The path you gave me doesn't work, check yourself before you wreck yourself.` or something along the lines of that.

So you are say there is nothing in the logs that are suspicious?

**Comment by Nexuzzzz** [comment]
nope, it didn't gave any errors. The wallpaper works when coding, but when going into the settings they are all invisible.

**Comment by Unthrottled** [comment]
That's odd. You are still able to modify the settings.json and see changes, even though the settings UI is invisible, right?

**Comment by Nexuzzzz** [comment]
> That's odd. You are still able to modify the settings.json and see changes, even though the settings UI is invisible, right?

no, once i change the wallpaper asset the settings UI is gone, i can still see the dropdown menu with all the options. But everything else is invisible, as you can see in the image.

**Comment by Unthrottled** [comment]
Sorry for not being clear.

You are still able to modify the settings.json by opening `Preferences: Open Settings (JSON)`, and editing the JSON? When you save the changes to the json, do the assets get installed?

**Comment by Nexuzzzz** [comment]
> Sorry for not being clear.
> 
> You are still able to modify the settings.json by opening `Preferences: Open Settings (JSON)`, and editing the JSON? When you save the changes to the json, do the assets get installed?

When i edit the settings.json file, the settings UI becomes invisibile, likewise with the UI installation of the custom asset. When i use the json option, the asset gets installed but the UI gets removed, but its still there (i can still hover over the input buttons and click stuff)

**Comment by Unthrottled** [comment]
I haven't been able to reproduce, but I think it may have to do with the custom images not being transparent. https://github.com/doki-theme/doki-theme-vscode/issues/178#issuecomment-1274055841

**Not Transparent**
<img width="1092" alt="Screen Shot 2022-10-11 at 5 45 46 PM" src="https://user-images.githubusercontent.com/15972415/195212362-067f9ac0-0c41-48c5-b1b7-53ff649ce570.png">

**Partially Transparent**
<img width="1136" alt="Screen Shot 2022-10-11 at 5 48 01 PM" src="https://user-images.githubusercontent.com/15972415/195212379-ca34751b-5f22-4d3d-8871-916ecfd46d56.png">

Finna close because cannot reproduce. Let me know if I need to try harder, and we can work something out about how I can reproduce.
